In [11]:
# defining a class
class Dog:
    pass

1. CLASS

In [12]:
print(Dog)


<class '__main__.Dog'>


2. OBJECT

In [13]:
bosko = Dog()
print(bosko)

3. ATTRIBUTE


In [14]:
# can bosko bark
# bosko.bark()

In [15]:
# creating a method/function 
def make_a_bark():
    return "Woof! Woof!"

In [16]:
# instantiate the method 
bosko.bark = make_a_bark
bosko.bark

<function __main__.make_a_bark()>

In [17]:
bosko.bark()

'Woof! Woof!'

In [18]:
# motina.bark()

In [19]:
# motina = Dog()
# motina.bark()

In [20]:
# motina.bark = make_a_bark
# motina.bark()

In [21]:
# defining an instant method
class Dog:
    def bark():
        return "I'm an instance method and woof! Woof!"

In [22]:
mailo = Dog()# instantiating an object
# instantiating is making an object exist
mailo.bark

<bound method Dog.bark of <__main__.Dog object at 0x000002722C367070>>

SELF

In [23]:
class Dog:
    def bark(self):
        return "I can actually bark"
new_mailo = Dog()
new_mailo.bark()        

'I can actually bark'

In [24]:
class Dog:
    def bark(self):
        return "I can actually bark"
    
    def who_am_i(self):
        return self  

In [25]:
simba = Dog()
simba.who_am_i()

In [26]:
print(simba)
print(simba.who_am_i())
print(simba.bark())

I can actually bark


In [27]:
# creating a class
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed
    def bark(self):
        return f"{self.name} says Woof! Woof!"
    

In [28]:
# calling the function/creating object of the class
my_dog = Dog("Rover", "Golden Retriever")
# print(my_dog.name)
# print(my_dog.breed)
print(my_dog.bark())

Rover says Woof! Woof!


In [29]:
my_dog.breed

'Golden Retriever'

In [30]:
# creating a class #__init__
#behaviours- activate,deactivate, deposit, withdraw, transfer, check balance
class BankAccount:
    def __init__(self, acc_no, balance):#instance method
        self.acc_no = acc_no#feature/attribute
        self.balance = balance
    def deposit(self, amount):
        self.balance += amount
        return self.balance
    def withdraw(self, amount):
        if amount > self.balance:
            raise Exception("Insufficient balance")
        
        self.balance -= amount
        return self.balance
    def check_balance(self):
        return self.balance     

In [31]:
# create an instance of a class/
# object 
my_acc = BankAccount("123456789", 1000)

In [32]:
# accessing attributes
print(my_acc.acc_no)
print(my_acc.balance)

123456789
1000


In [33]:
# call object methods(functions that we create inside a class)part1
# behavior
print(my_acc.check_balance())
my_acc.deposit(500)
print(my_acc.check_balance())
my_acc.withdraw(200)
print(my_acc.check_balance())


1000
1500
1300


In [34]:
# calling the instance method2
print(my_acc.deposit(500))
print(my_acc.withdraw(200))
print(my_acc.check_balance())

1800
1600
1600


## Inheritance 
- Allows a new class(child) to inherite attributes & methods from an existing
class(parent)
- Python supports multiple inheritans; where a child can inherit from multiple classes

In [35]:
#creating a class animal
class Animal:
    def __init__(self, name):
        self.name = name
    def move(self):
        return f"{self.name} is moving"
    

In [36]:
class Dog(Animal):
    def bark(self):
        return f"{self.name}  Woof! Woof!"
    
class bird(Animal):
    def fly(self):
        return f"{self.name} can fly"    

In [37]:
# creating instance of the class dog and bird
my_dog = Dog("Rover")
print(my_dog.move())
print(my_dog.bark())


Rover is moving
Rover  Woof! Woof!


# creating machine learning pipeline using OOP

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

# create a class for machine learning pipeline
class reg_model:
    def __init__(self, X, y, model):
        self.X = X
        self.y = y
        self.model = model
        self.scaler = StandardScaler()  # tool
    def split_data(self, test_size=0.2, random_state=7):
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(self.X, self.y, test_size=test_size, random_state=random_state)
    def preprocess(self):
        self.X_train_scaled = self.scaler.fit_transform(self.X_train)
    def train(self):
        self.model.fit(self.X_train_scaled, self.y_train)
    def predict(self):
        self.y_pred = self.model.predict(self.X_test)
        return self.y_pred
    def evaluate(self):
        predictions = self.model.predict(self.X_test)
        mse = mean_squared_error(self.y_test, predictions)
        return mse


In [39]:
# sample data
df = pd.DataFrame({
    "feature1": [1, 2, 3, 4, 5],
    "feature2": [10, 20, 30, 40, 50],
    "target": [3, 6, 9, 12, 15]     
})
X = df.drop(columns=['target'])
y = df['target']

In [40]:
# Regression
model = LinearRegression()
reg = reg_model(X, y, model)
reg.split_data()
reg.preprocess()
reg.train()
reg.predict()



array([28.94756081])

In [41]:
# classification
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
reg = reg_model(X, y, model)
reg.split_data()
reg.preprocess()
reg.train()
reg.predict()

array([15], dtype=int64)

In [42]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

# Load the Ames housing dataset
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv"
data = pd.read_csv(url)
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino


In [43]:
data.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [46]:
# Filling missing valuesdata
data['horsepower'].fillna(data['horsepower'].mean(), inplace=True)


In [47]:
# Select features and target variable
X = data[['horsepower']]
y = data['mpg'] 

In [51]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)
print(X_train.shape, X_test.shape) 
print(y_train.shape, y_test.shape)

(318, 1) (80, 1)
(318,) (80,)


In [52]:
# Fitting the model
model = LinearRegression()
model.fit(X_train, y_train) 

LinearRegression()

In [53]:
# Prediction
y_pred = model.predict(X_test)      
print(y_pred[:5])  # Print first 5 predictions


[28.32642283 22.48722784 30.2202158  28.16860675 30.37803188]


In [ ]:
print(y_test[:5])  

148    26.0
389    22.0
350    34.7
52     30.0
332    29.8
Name: mpg, dtype: float64


In [55]:
# Checking the metrics
mse = mean_squared_error(y_test, y_pred)
mse

21.027332133054944

In [57]:
# Prediction should match y_train
y_train_pred = model.predict(X_train)

In [59]:
# Cchecking underfitting and overfitting
mse_training = np.sqrt(mean_squared_error(y_train, y_train_pred))
mse_test = np.sqrt(mean_squared_error(y_test, y_pred))
print(mse_training)
print(mse_test)

5.061770024869303
4.585556905442886
